# Generated by Django 3.2 on 2022-01-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('cate1', 'slide1'), ('post', 'post')], default='post', max_length=20),
        ),
    ]
