# Generated by Django 3.2 on 2022-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0002_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('post', 'post'), ('jeans', 'jeans')], default='post', max_length=20),
        ),
    ]
