# Generated by Django 3.2 on 2022-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0004_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('jeans', 'jeans'), ('shoes', 'shoes'), ('post', 'post'), ('shirts', 'shirts')], default='post', max_length=20),
        ),
    ]
