# Generated by Django 3.2 on 2022-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0006_auto_20220111_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('shoes', 'shoes'), ('jeans', 'jeans'), ('shirts', 'shirts'), ('post', 'post')], default='post', max_length=20),
        ),
    ]
