# Generated by Django 3.2 on 2022-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0008_auto_20220114_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='bodys',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='titles',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='grops',
        ),
        migrations.AddField(
            model_name='about',
            name='grop',
            field=models.CharField(choices=[('jeanss', 'jeanss'), ('post', 'postt')], default='jeanss', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('jeans', 'jeans'), ('post', 'post'), ('shoes', 'shoes'), ('shirts', 'shirts')], default='post', max_length=20),
        ),
    ]
