# Generated by Django 3.2 on 2022-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0009_auto_20220114_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='grop',
            field=models.CharField(choices=[('post', 'postt'), ('jeanss', 'jeanss')], default='jeanss', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('shoes', 'shoes'), ('post', 'post'), ('shirts', 'shirts'), ('jeans', 'jeans')], default='post', max_length=20),
        ),
    ]
