# Generated by Django 3.2 on 2022-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0010_auto_20220114_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('shirts', 'shirts'), ('about', 'about'), ('shoes', 'shoes'), ('jeans', 'jeans'), ('post', 'post')], default='post', max_length=20),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
