# Generated by Django 3.2 on 2022-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0012_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('advantage3', 'advantage3'), ('post', 'post'), ('advantage2', 'advantage2'), ('about', 'about'), ('advantage1', 'advantage1')], default='post', max_length=20),
        ),
    ]
