# Generated by Django 3.2 on 2022-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0013_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('post', 'post'), ('advantage2', 'advantage2'), ('advantage1', 'advantage1'), ('advantage3', 'advantage3'), ('about', 'about')], default='post', max_length=20),
        ),
    ]
