# Generated by Django 3.2 on 2022-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0014_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('catherinesoft', 'catherinesoft'), ('advantage3', 'advantage3'), ('advantage1', 'advantage1'), ('advantage2', 'advantage2'), ('about', 'about'), ('post', 'post'), ('timycake', 'timycake'), ('johnhenry', 'johnhenry'), ('jayzoona', 'jayzoona')], default='post', max_length=20),
        ),
    ]
