# Generated by Django 3.2 on 2022-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0015_alter_post_grop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('advantage2', 'advantage2'), ('advantage3', 'advantage3'), ('advantage1', 'advantage1'), ('catherinesoft', 'catherinesoft'), ('jayzoona', 'jayzoona'), ('post', 'post'), ('about', 'about'), ('johnhenry', 'johnhenry'), ('timycake', 'timycake')], default='post', max_length=20),
        ),
    ]
