# Generated by Django 3.2 on 2022-01-15 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0016_auto_20220114_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('about', 'about'), ('advantage2', 'advantage2'), ('jayzoona', 'jayzoona'), ('timycake', 'timycake'), ('advantage1', 'advantage1'), ('post', 'post'), ('catherinesoft', 'catherinesoft'), ('johnhenry', 'johnhenry'), ('advantage3', 'advantage3')], default='post', max_length=20),
        ),
    ]
