# Generated by Django 3.2 on 2022-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0017_auto_20220115_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('jayzoona', 'jayzoona'), ('advantage2', 'advantage2'), ('catherinesoft', 'catherinesoft'), ('advantage1', 'advantage1'), ('post', 'post'), ('johnhenry', 'johnhenry'), ('about', 'about'), ('timycake', 'timycake'), ('advantage3', 'advantage3')], default='post', max_length=20),
        ),
    ]
